
version: 2

models:
  - name: im_in_new_model_folder
    description: "Gives us all the regions. It is materialize as a 'View' since that's how it is setup by default **See dbt_project.yml"
    columns:
      - name: R_REGIONKEY
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
          - accepted_values:
              values: [0, 1, 2, 3, 4]
              quote: False

  