
version: 2

models:
  - name: advanced_config_test
    description: "This template will only be used to test advanced configurations like Alias, schema and database."
    columns:
      - name: c_custkey
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: testing_hooks
    description: "This model is only used to test hooks and see in snowflake if permissions are transferred to role and user"
    columns:
      - name: r_regionkey
        description: "The primary key for this table"
        tests:
          - unique
          - not_null          

  - name: testing_snapshots
    description: "I'm using this model to test snapshots in order to track changing data over time"
    columns:
       - name: id
         description: "The primary key for this table"
         tests:
         - unique    


  - name: testing_macro_group_by
    description: "This macro will be used to group  some element using a for loop that take N as the number of aggregation you want to perform"
     
  - name: testing_macro_segmentation
    description: "This macro will be used to group some segment from the table costumer in sample_data TPCH_SF1"

  - name: testing_tags
    description: "This model is use to see if the tags with 'dbt run --model tag:test tag' is working"   

sources:
  - name: sample
    database: sample_data
    schema: tpch_sf1
    tables:
      - name: customer
      - name: orders
